set first=FIRST_NAME
set last=LAST_NAME
set phone=PHONE_NUM

del finisher.txt
echo DO NOT EDIT THIS FILE > finisher.txt

set /A count=0
:loop
set /a count=%count%+1
START py src\bot.py --first %first% --last %last% --phone %phone%
if %count% neq 6 goto loop
