set first=John
set last=Smith
set phone=6127485142

del finisher.txt
echo DO NOT EDIT THIS FILE > finisher.txt

set /A count=0
:loop
set /a count=%count%+1
START py src\bot.py --test --first %first% --last %last% --phone %phone%
if %count% neq 6 goto loop
